/* Kalidad Pharmacy — Firebase live pharmacist chat layer. */
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, signInAnonymously, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, collection, addDoc, doc, getDoc, updateDoc, query, where, onSnapshot, serverTimestamp, limit } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
const cfg=window.KALIDAD_FIREBASE_CONFIG;if(!cfg||!cfg.apiKey||cfg.apiKey.indexOf('PASTE_')===0)throw Error('Firebase web configuration is not installed.');
const app=getApps().length?getApps()[0]:initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);
export async function ensureCustomer(){if(auth.currentUser&&!auth.currentUser.isAnonymous)return auth.currentUser;await signInAnonymously(auth);return new Promise((resolve,reject)=>{const stop=onAuthStateChanged(auth,u=>{if(u){stop();resolve(u)}});setTimeout(()=>{stop();reject(Error('Firebase authentication timed out.'))},10000)})}
export async function createHandoff({history=[],reason='clinical-question'}={}){const user=await ensureCustomer(),ref=await addDoc(collection(db,'conversations'),{customerUid:user.uid,status:'waiting',channel:'website',reason:String(reason).slice(0,120),privacyConsent:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastMessageAt:serverTimestamp()});for(const m of(Array.isArray(history)?history.slice(-12):[])){const body=String(m?.content||'').trim().slice(0,2000);if(body)await addDoc(collection(db,'conversations',ref.id,'messages'),{senderUid:user.uid,senderType:m.role==='user'?'customer':'assistant',body,createdAt:serverTimestamp()})}await addDoc(collection(db,'conversations',ref.id,'messages'),{senderUid:'system',senderType:'system',body:'The AI assistant handed this conversation to the Kalidad pharmacist team.',createdAt:serverTimestamp()});return ref.id}
export async function sendCustomerMessage(conversationId,body){const user=await ensureCustomer(),text=String(body||'').trim().slice(0,2000);if(!text)return;await addDoc(collection(db,'conversations',conversationId,'messages'),{senderUid:user.uid,senderType:'customer',body:text,createdAt:serverTimestamp()});await updateDoc(doc(db,'conversations',conversationId),{updatedAt:serverTimestamp(),lastMessageAt:serverTimestamp(),status:'active'})}
export function watchCustomerMessages(id,cb){const q=query(collection(db,'conversations',id,'messages'),limit(100));return onSnapshot(q,s=>cb(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>((a.createdAt?.seconds||0)-(b.createdAt?.seconds||0))))) }
export async function getCustomerConversation(id){const u=await ensureCustomer(),s=await getDoc(doc(db,'conversations',id));if(!s.exists()||s.data().customerUid!==u.uid)throw Error('Conversation not found.');return{id:s.id,...s.data()}}
export async function staffLogin(email,password){const cred=await signInWithEmailAndPassword(auth,email,password),s=await getDoc(doc(db,'staff',cred.user.uid));if(!s.exists()||!['pharmacist','admin'].includes(s.data().role)){await signOut(auth);throw Error('This account is not authorised for the pharmacist portal.')}return{user:cred.user,profile:s.data()}}
export async function staffProfile(){const u=auth.currentUser;if(!u||u.isAnonymous)return null;const s=await getDoc(doc(db,'staff',u.uid));return s.exists()?{user:u,...s.data()}:null}
export function watchWaitingConversations(cb){return onSnapshot(query(collection(db,'conversations'),where('status','==','waiting'),limit(50)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>((b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)))))}
export function watchActiveConversations(cb){return onSnapshot(query(collection(db,'conversations'),where('status','==','active'),limit(50)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>((b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0)))))}
export function watchConversation(id,cb){return onSnapshot(doc(db,'conversations',id),s=>cb(s.exists()?{id:s.id,...s.data()}:null))}
export function watchStaffMessages(id,cb){return watchCustomerMessages(id,cb)}
export async function sendStaffMessage(id,body){const u=auth.currentUser;if(!u||u.isAnonymous)throw Error('Staff login required.');const text=String(body||'').trim().slice(0,2000);if(!text)return;await addDoc(collection(db,'conversations',id,'messages'),{senderUid:u.uid,senderType:'staff',body:text,createdAt:serverTimestamp()});await updateDoc(doc(db,'conversations',id),{status:'active',assignedStaffUid:u.uid,updatedAt:serverTimestamp(),lastMessageAt:serverTimestamp()})}
export async function updateConversation(id,fields){const a={};if(['waiting','active','resolved'].includes(fields.status))a.status=fields.status;if(fields.assignedStaffUid)a.assignedStaffUid=fields.assignedStaffUid;a.updatedAt=serverTimestamp();await updateDoc(doc(db,'conversations',id),a)}
export async function logoutStaff(){await signOut(auth)}
