import { useEffect, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { collection, doc, getDoc, getDocs, orderBy, query, where } from 'firebase/firestore';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { ArrowRight, CheckCircle2, ChevronRight, Menu, MessageCircle, Package, Search, ShoppingCart, ShieldCheck, Stethoscope, X } from 'lucide-react';
import { auth, db } from './firebase';

const nav = [
  ['/', 'Home'], ['/services', 'Services'], ['/wellness', 'Wellness'], ['/about', 'About us'],
  ['/news', 'News'], ['/careers', 'Careers'], ['/contact', 'Contact us'], ['/store', 'Shop']
];

function Layout({ children }) {
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();
  return <>
    <header className="site-header"><div className="container nav-wrap">
      <Link className="brand" to="/" onClick={() => setOpen(false)}><span className="brand-mark">K</span><span><b>KALIDAD</b><small>PHARMACY</small></span></Link>
      <nav className="desktop-nav">{nav.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'}>{label}</NavLink>)}</nav>
      <div className="nav-actions"><Link className="icon-link" to="/store/cart" aria-label="Cart"><ShoppingCart size={20}/></Link><button className="btn btn-primary nav-chat" onClick={() => navigate('/contact')}><MessageCircle size={17}/> Chat with us</button><button className="menu-btn" onClick={() => setOpen(v => !v)} aria-label="Menu">{open ? <X/> : <Menu/>}</button></div>
    </div>{open && <nav className="mobile-nav">{nav.map(([to,label]) => <NavLink key={to} to={to} onClick={() => setOpen(false)}>{label}</NavLink>)}<Link to="/admin/login" onClick={() => setOpen(false)}>Admin portal</Link></nav>}</header>
    <main>{children}</main>
    <footer><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-mark">K</span><span><b>KALIDAD</b><small>PHARMACY</small></span></div><p>Trusted community pharmacy and wellness care in Fort Portal, Uganda.</p></div><div><h4>Quick links</h4>{nav.slice(0,6).map(([to,label]) => <Link key={to} to={to}>{label}</Link>)}</div><div><h4>Visit us</h4><p>Kisenyi, Fort Portal, Uganda</p><p>Everyday</p><p>Message us on WhatsApp</p></div></div><div className="footer-bottom">© {new Date().getFullYear()} Kalidad Pharmacy. Your health, your wealth.</div></footer>
  </>;
}

const services = [
  ['Prescription care','Prescription dispensing, refills and pharmacist counselling.'],
  ['Health checks','Convenient blood pressure, glucose and basic wellness checks.'],
  ['Wellness products','Vitamins, personal care, skincare, baby care and health essentials.'],
  ['Digital care','Connect with the pharmacy team for guidance and service access.'],
  ['Medicine support','Safe use guidance, adherence support and medicine information.'],
  ['Order & delivery','Place orders and arrange convenient local collection or delivery.']
];

function Home() { return <>
  <section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><i/> Open every day</span><h1>Your health.<br/><em>Your wealth.</em></h1><p>Professional pharmacy care, wellness essentials and trusted guidance for you and your family.</p><div className="actions"><Link className="btn btn-primary" to="/store">Explore products <ArrowRight size={18}/></Link><Link className="btn btn-outline" to="/services">Our services</Link></div></div><div className="hero-card"><div className="hero-card-top"><ShieldCheck size={34}/><span>Trusted pharmacy care</span></div><h2>Care that feels personal.</h2><p>From prescriptions to everyday wellness, our team is here to help you make confident health decisions.</p><div className="mini-grid"><div><b>24/7</b><small>Support</small></div><div><b>5+</b><small>Years serving</small></div><div><b>Local</b><small>Fort Portal</small></div></div></div></div></section>
  <section className="section"><div className="container"><SectionTitle kicker="What we do" title="Pharmacy care, beyond the counter" text="A modern community pharmacy experience built around access, safety and genuine human care."/><div className="cards">{services.map(([t,d]) => <article className="card" key={t}><span className="service-icon"><Stethoscope size={22}/></span><h3>{t}</h3><p>{d}</p><Link to="/services">Learn more <ChevronRight size={16}/></Link></article>)}</div></div></section>
  <section className="stats"><div className="container stats-grid"><div><b>5+</b><span>Years serving our community</span></div><div><b>24/7</b><span>Pharmacy support</span></div><div><b>100%</b><span>Patient-focused care</span></div></div></section>
</>; }
function SectionTitle({kicker,title,text}) { return <div className="section-title"><span>{kicker}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function Page({title,kicker='Kalidad Pharmacy',text,children}) { return <><section className="page-head"><div className="container"><span>{kicker}</span><h1>{title}</h1>{text && <p>{text}</p>}</div></section>{children}</> }
function About(){return <Page title="About us" text="A trusted community pharmacy serving Fort Portal with professional care and practical wellness support."><section className="section"><div className="container two-col"><div><SectionTitle kicker="Our purpose" title="Healthcare with a human touch" text="Kalidad Pharmacy combines professional dispensing with accessible wellness care. We aim to make every visit clear, respectful and useful."/><div className="check-list"><p><CheckCircle2/> Licensed, community-focused pharmacy care</p><p><CheckCircle2/> Practical medicine and wellness guidance</p><p><CheckCircle2/> Everyday access to health essentials</p></div></div><div className="quote-card"><ShieldCheck size={42}/><h3>Trusted. Local. Personal.</h3><p>Our goal is simple: help people in our community look after their health with confidence.</p></div></div></section></Page>}
function Services(){return <Page title="Our services" text="Professional pharmacy and wellness services designed around your everyday health needs."><section className="section"><div className="container"><div className="cards">{services.map(([t,d])=><article className="card large" key={t}><span className="service-icon"><Stethoscope size={24}/></span><h3>{t}</h3><p>{d}</p><Link className="text-link" to="/contact">Access this service <ArrowRight size={16}/></Link></article>)}</div></div></section></Page>}
function Wellness(){return <Page title="Wellness catalogue" text="Explore everyday nutritional, hygiene, skincare, body-care and baby-care essentials."><section className="section"><div className="container"><div className="wellness-grid">{['Nutritional Supplements & Boosters','Personal Hygiene & Oral Care','Skincare & Body Care','Baby Care Essentials'].map((x,i)=><article className="wellness-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Browse carefully selected wellness essentials and speak to our pharmacy team for guidance.</p><Link to="/store">Explore catalogue <ArrowRight size={16}/></Link></article>)}</div></div></section></Page>}
function Contact(){return <Page title="Contact us" text="Reach Kalidad Pharmacy for prescriptions, product questions, service access or order support."><section className="section"><div className="container contact-grid"><div className="contact-card"><h2>Let's talk</h2><p>Kisenyi, Fort Portal, Uganda</p><p>Open every day</p><a className="btn btn-primary" href="https://wa.me/256000000000"><MessageCircle size={18}/> Message us</a></div><form className="form-card" onSubmit={e=>{e.preventDefault();alert('Thank you. Please message us on WhatsApp for the fastest response.')}}><label>Name<input required/></label><label>Email<input type="email" required/></label><label>How can we help?<textarea rows="5" required/></label><button className="btn btn-primary">Send enquiry</button></form></div></section></Page>}
function Careers(){return <Page title="Careers" text="Join a team committed to professional, accessible and compassionate pharmacy care."><section className="section"><div className="container centered"><h2>Build better pharmacy care with us.</h2><p>Check current opportunities and submit your application through our careers process.</p><Link className="btn btn-primary" to="/contact">Ask about opportunities <ArrowRight size={18}/></Link></div></section></Page>}
function News(){return <Page title="News & updates" text="Health, wellness and pharmacy updates from Kalidad Pharmacy."><section className="section"><div className="container"><div className="empty-state"><Package size={40}/><h2>Updates are coming</h2><p>This React-powered section is ready for Firebase-backed articles and announcements.</p></div></div></section></Page>}

function Store(){const [products,setProducts]=useState([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');useEffect(()=>{(async()=>{try{const snap=await getDocs(query(collection(db,'products'),where('active','==',true),orderBy('name')));setProducts(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error(e)}finally{setLoading(false)}})()},[]);const shown=products.filter(p=>p.name?.toLowerCase().includes(search.toLowerCase()));return <Page title="Shop" kicker="Kalidad Store" text="Browse the live Firebase product catalogue."><section className="section"><div className="container"><div className="store-toolbar"><div className="search"><Search size={18}/><input placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)}/></div><Link className="btn btn-outline" to="/store/cart"><ShoppingCart size={18}/> Cart</Link></div>{loading?<div className="empty-state">Loading catalogue…</div>:shown.length?<div className="product-grid">{shown.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-state"><Package size={40}/><h2>No products found</h2><p>Once the Kalidad catalogue is loaded into Firebase, products will appear here.</p></div>}</div></section></Page>}
function ProductCard({product}){const add=()=>{const cart=JSON.parse(localStorage.getItem('kalidad-cart')||'[]');const found=cart.find(x=>x.id===product.id);if(found)found.quantity+=1;else cart.push({id:product.id,name:product.name,price:Number(product.salePrice??product.price??0),image:product.image||'',quantity:1});localStorage.setItem('kalidad-cart',JSON.stringify(cart));alert('Added to cart');};return <article className="product-card"><div className="product-image">{product.image?<img src={product.image} alt=""/>:<Package size={42}/>}</div><div className="product-body"><span>{product.categoryName||'Health essential'}</span><h3>{product.name}</h3><p>{product.description||'Quality pharmacy product.'}</p><strong>UGX {Number(product.salePrice??product.price??0).toLocaleString()}</strong><button className="btn btn-primary" onClick={add}>Add to cart</button></div></article>}
function Cart(){const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('kalidad-cart')||'[]'));const update=(i,d)=>{const next=cart.map((x,n)=>n===i?{...x,quantity:Math.max(1,x.quantity+d)}:x);setCart(next);localStorage.setItem('kalidad-cart',JSON.stringify(next))};const total=cart.reduce((s,x)=>s+x.price*x.quantity,0);return <Page title="Your cart" kicker="Kalidad Store"><section className="section"><div className="container">{!cart.length?<div className="empty-state"><ShoppingCart size={42}/><h2>Your cart is empty</h2><Link className="btn btn-primary" to="/store">Browse products</Link></div>:<div className="cart-layout"><div className="cart-list">{cart.map((x,i)=><article className="cart-row" key={x.id}><div><h3>{x.name}</h3><p>UGX {x.price.toLocaleString()}</p></div><div className="qty"><button onClick={()=>update(i,-1)}>−</button><b>{x.quantity}</b><button onClick={()=>update(i,1)}>+</button></div></article>)}</div><aside className="summary"><h2>Order summary</h2><p><span>Subtotal</span><b>UGX {total.toLocaleString()}</b></p><Link className="btn btn-primary full" to="/store/checkout">Proceed to checkout</Link></aside></div>}</div></section></Page>}
function Checkout(){const cart=JSON.parse(localStorage.getItem('kalidad-cart')||'[]');const total=cart.reduce((s,x)=>s+x.price*x.quantity,0);return <Page title="Checkout" kicker="Kalidad Store"><section className="section"><div className="container checkout"><div className="form-card"><h2>Customer details</h2><label>Full name<input required/></label><label>Phone<input required/></label><label>Delivery / collection notes<textarea rows="4"/></label><button className="btn btn-primary" onClick={()=>alert('Customer order flow is connected to the Firebase order model; final submission wiring is the next test step.')}>Place order</button></div><div className="summary"><h2>Total</h2><strong className="total">UGX {total.toLocaleString()}</strong><p>Payment status: pending</p><p>Order status: pending</p></div></div></section></Page>}
function StoreLogin(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const navigate=useNavigate();const submit=async e=>{e.preventDefault();setError('');try{await signInWithEmailAndPassword(auth,email.trim(),password);const user=auth.currentUser;const snap=await getDoc(doc(db,'users',user.uid));const p=snap.exists()?snap.data():null;if(!p||!['customer'].includes(p.role)||p.active===false)throw new Error('This account is not authorized for the customer portal.');navigate('/store/account')}catch(err){setError(err.message)}};return <AuthCard title="Customer sign in" onSubmit={submit} error={error} fields={<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label></>}/>}
function AuthCard({title,onSubmit,error,fields}){return <section className="auth-page"><form className="form-card auth-card" onSubmit={onSubmit}><span className="brand">KALIDAD PHARMACY</span><h1>{title}</h1>{fields}<button className="btn btn-primary full">Sign in</button>{error&&<p className="error">{error}</p>}<Link to="/store/signup">Create a customer account</Link></form></section>}
function Account(){const [user,setUser]=useState(auth.currentUser);useEffect(()=>onAuthStateChanged(auth,setUser),[]);if(!user)return <Navigate to="/store/login"/>;return <Page title="My account" kicker="Customer portal"><section className="section"><div className="container account"><div className="quote-card"><h2>Welcome back</h2><p>{user.email}</p><Link className="btn btn-primary" to="/store/orders">View my orders</Link><button className="btn btn-outline" onClick={()=>signOut(auth)}>Sign out</button></div></div></section></Page>}

function AdminLogin(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [profile,setProfile]=useState(null);const navigate=useNavigate();const submit=async e=>{e.preventDefault();setError('');try{const cred=await signInWithEmailAndPassword(auth,email.trim(),password);const snap=await getDoc(doc(db,'users',cred.user.uid));const p=snap.exists()?snap.data():null;if(!p||!['admin','superadmin','staff'].includes(p.role)||p.active===false){await signOut(auth);throw new Error('This account is not authorized for the admin portal.')}setProfile(p)}catch(err){setError(err.message)}};if(profile)return <section className="auth-page"><div className="form-card auth-card"><CheckCircle2 className="success-icon" size={46}/><h1>Admin details confirmed</h1><p>Authenticated successfully.</p><div className="confirmation"><span>Name</span><b>{[profile.firstName,profile.lastName].filter(Boolean).join(' ')||'Admin user'}</b><span>Email</span><b>{profile.email||email}</b><span>Role</span><b>{profile.role}</b><span>Status</span><b>Active</b></div><button className="btn btn-primary full" onClick={()=>navigate('/admin')}>Continue to dashboard</button></div></section>;return <AuthCard title="Admin portal" onSubmit={submit} error={error} fields={<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label></>}/>}
function RequireAdmin({children}){const [state,setState]=useState('checking');useEffect(()=>{const unsub=onAuthStateChanged(auth,async user=>{if(!user){setState('denied');return}const snap=await getDoc(doc(db,'users',user.uid));const p=snap.exists()?snap.data():null;setState(p&&['admin','superadmin','staff'].includes(p.role)&&p.active!==false?'ok':'denied')});return unsub},[]);if(state==='checking')return <div className="empty-state">Checking admin access…</div>;return state==='ok'?children:<Navigate to="/admin/login"/>}
function Admin(){return <RequireAdmin><Page title="Pharmacy dashboard" kicker="Kalidad Admin" text="Manage catalogue, inventory, customer orders and website content."><section className="section"><div className="container admin-grid">{[['/admin/products','Products','Manage the Firebase catalogue and categories.'],['/admin/product-edit','Add product','Create products with categories and images.'],['/admin/orders','Orders','Review customer orders.'],['/admin/customers','Customers','View registered customer profiles.'],['/admin/content','Website content','Manage selected Firebase-backed content.']].map(([to,t,d])=><Link className="admin-card" to={to} key={to}><Package/><h2>{t}</h2><p>{d}</p><ArrowRight/></Link>)}</div></section></Page></RequireAdmin>}
function AdminProducts(){return <RequireAdmin><AdminList title="Products" collectionName="products"/></RequireAdmin>}
function AdminList({title,collectionName}){const [rows,setRows]=useState([]);useEffect(()=>{getDocs(collection(db,collectionName)).then(s=>setRows(s.docs.map(d=>({id:d.id,...d.data()})))).catch(console.error)},[collectionName]);return <Page title={title} kicker="Kalidad Admin"><section className="section"><div className="container"><div className="admin-table">{rows.map(r=><div className="admin-row" key={r.id}><div><b>{r.name||r.email||r.id}</b><small>{r.categoryName||r.role||'—'}</small></div><span>{r.active===false?'Inactive':'Active'}</span></div>)}{!rows.length&&<div className="empty-state">No records yet.</div>}</div></div></section></Page>}
function AdminOrders(){return <RequireAdmin><AdminList title="Orders" collectionName="orders"/></RequireAdmin>}
function AdminCustomers(){return <RequireAdmin><AdminList title="Customers" collectionName="users"/></RequireAdmin>}
function AdminSimple({title}){return <RequireAdmin><Page title={title} kicker="Kalidad Admin"><section className="section"><div className="container empty-state"><Package size={40}/><h2>{title} editor</h2><p>The React admin shell is ready for the corresponding Firebase workflow.</p></div></section></Page></RequireAdmin>}
function ProductDetail(){const {id}=useParams();const [product,setProduct]=useState(null);useEffect(()=>getDoc(doc(db,'products',id)).then(s=>s.exists()&&setProduct({id:s.id,...s.data()})),[id]);if(!product)return <div className="empty-state">Loading product…</div>;return <Page title={product.name} kicker={product.categoryName||'Product'}><section className="section"><div className="container product-detail"><div className="product-image big">{product.image?<img src={product.image} alt=""/>:<Package size={60}/>}</div><div><p>{product.description}</p><h2>UGX {Number(product.salePrice??product.price??0).toLocaleString()}</h2><Link className="btn btn-primary" to="/store">Back to store</Link></div></div></section></Page>}

export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/wellness" element={<Wellness/>}/><Route path="/contact" element={<Contact/>}/><Route path="/careers" element={<Careers/>}/><Route path="/news" element={<News/>}/><Route path="/store" element={<Store/>}/><Route path="/store/product/:id" element={<ProductDetail/>}/><Route path="/store/cart" element={<Cart/>}/><Route path="/store/checkout" element={<Checkout/>}/><Route path="/store/login" element={<StoreLogin/>}/><Route path="/store/account" element={<Account/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<Admin/>}/><Route path="/admin/products" element={<AdminProducts/>}/><Route path="/admin/orders" element={<AdminOrders/>}/><Route path="/admin/customers" element={<AdminCustomers/>}/><Route path="/admin/product-edit" element={<AdminSimple title="Product"/>}/><Route path="/admin/content" element={<AdminSimple title="Website content"/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Layout>}
