import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, useLocation, useNavigate, useParams, Routes, Route, Link, Navigate } from 'react-router-dom';
import { onAuthStateChanged, signOut, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile } from 'firebase/auth';
import { collection, getDocs, query, where, orderBy, limit, doc, setDoc, serverTimestamp, addDoc, getDoc } from 'firebase/firestore';
import { auth, db } from './firebase';
import { Menu, X, ShoppingCart, UserRound, Moon, Sun, MapPin, Phone, Clock, ArrowRight, HeartPulse, ShieldCheck, Truck, Search, LogOut, Package, LayoutDashboard } from 'lucide-react';
import './styles.css';

const BASE = '/Kalidad-Pharmacy/';
const nav = [['Home','/'],['Services','/services'],['Contact Us','/contact'],['Careers','/careers'],['News','/news'],['About Us','/about']];
const pages = {
  '/services':['Care centred around you','What we offer','From prescription filling and free health checks to wellness, personal care and baby essentials.','services-hero.webp'],
  '/contact':['We are here when you need us','Contact Kalidad','Reach our pharmacy team for questions, refills, consultations and delivery support.','we deliver.webp'],
  '/careers':['Build a career that cares','Join Kalidad','Grow with a community pharmacy focused on people, professionalism and better health.','careers-hero.webp'],
  '/news':['Health insights from Kalidad','News & wellness','Practical health information, pharmacy updates and wellness ideas for everyday life.','Free health checks.webp'],
  '/about':['Trusted care, close to home','About Kalidad','A neighbourhood pharmacy serving Fort Portal with professional care and everyday health essentials.','about-hero-desktop.webp'],
  '/otc-wellness':['Everyday wellness, made simple','Wellness catalogue','Explore personal hygiene, skincare, body care, baby care and nutritional wellness products.','wellness-skincare-hero.webp'],
  '/nutritional-supplements':['Nutritional Supplements & Boosters','Wellness','Support everyday nutrition with carefully selected vitamins and supplements.','1000521632.webp'],
  '/personal-hygiene-oral-care':['Personal Hygiene & Oral Care','Wellness','Everyday essentials for clean, confident and healthy routines.','1000524892.webp'],
  '/skincare-body-care':['Skincare & Body Care','Wellness','Body and skincare essentials selected for everyday self-care.','wellness-skincare-hero.webp'],
  '/baby-care':['Baby Care Essentials','Wellness','Gentle everyday care for babies and growing families.','Care for your family.webp'],
  '/prescription-filling':['Prescription Filling','Pharmacy service','Reliable prescription support with professional pharmacist review.','Prescription-filling.webp'],
  '/pharmacist-consultation':['Pharmacist Consultation','Pharmacy service','Speak with a pharmacist about medicines, minor ailments and wellness.','Pharmacist consultation.webp'],
  '/health-checks':['Free Health Checks','Pharmacy service','Accessible checks and practical guidance to help you stay on top of your health.','Free health checks.webp'],
  '/same-day-delivery':['Same-day Delivery','Pharmacy service','Convenient delivery for eligible orders around Fort Portal.','we deliver.webp'],
  '/refill-reminders':['Refill Reminders','Digital care','Keep regular medicines on schedule with simple refill support.','Prescription-filling.webp'],
  '/routine-health-checks':['Routine Health Checks','Digital care','Practical screening and prevention support for everyday health.','Free health checks.webp'],
  '/family-care':['Family Care','Wellness','Health and wellness resources for the whole family.','Care for your family.webp']
};

function useTheme(){const [dark,setDark]=useState(()=>localStorage.getItem('kalidad-theme')==='dark');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('kalidad-theme',dark?'dark':'light')},[dark]);return [dark,()=>setDark(v=>!v)]}
function useCart(){const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('kalidad-cart')||'[]'));useEffect(()=>localStorage.setItem('kalidad-cart',JSON.stringify(cart)),[cart]);const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]});return {cart,setCart,add}}

function Header({user,count,dark,toggle}){const [open,setOpen]=useState(false);const loc=useLocation();return <><div className="topbar"><div><MapPin size={14}/> Kisenyi, Fort Portal, Uganda</div><div><Phone size={14}/> +256 759 845 260 · +256 772 292 177 <span>•</span><Clock size={14}/> OPEN 24/7</div><div className="socials">Follow us: Instagram · X · WhatsApp · LinkedIn</div></div><header><div className="header-inner"><Link to="/" className="brand"><img src={`${BASE}kalidad-logo.png`} alt="Kalidad Pharmacy"/><span><b>KALIDAD</b><em>PHARMACY</em></span></Link><nav>{nav.map(([n,p])=><Link key={p} className={loc.pathname===p?'active':''} to={p}>{n}</Link>)}</nav><div className="actions"><Link className="icon-btn" to="/store"><ShoppingCart/><span>Cart ({count})</span></Link><Link className="account-btn" to={user?'/store/account':'/store/login'}><UserRound/><span>My Account</span></Link><Link className="shop-btn" to="/store"><ShoppingCart/><span>Shop Online</span></Link><button className="icon-btn theme" onClick={toggle}>{dark?<Sun/>:<Moon/>}</button><button className="menu-btn" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<div className="mobile-nav">{nav.map(([n,p])=><Link key={p} onClick={()=>setOpen(false)} to={p}>{n}</Link>)}<Link onClick={()=>setOpen(false)} to="/store">Shop Online</Link><Link onClick={()=>setOpen(false)} to={user?'/store/account':'/store/login'}>My Account</Link><Link onClick={()=>setOpen(false)} to="/admin/login">Staff / Admin</Link></div>}</header></>}
function Footer(){return <footer><div className="footer-grid"><div><img className="footer-logo" src={`${BASE}kalidad-logo.png`} alt="Kalidad Pharmacy"/><p>Professional pharmacy care, wellness and everyday health essentials for our community.</p></div><div><h4>Explore</h4>{nav.map(([n,p])=><Link key={p} to={p}>{n}</Link>)}<Link to="/store">Shop Online</Link></div><div><h4>Visit Us</h4><p>Kisenyi, Fort Portal, Uganda</p><p>Everyday · 24/7</p><Link to="/admin/login">Staff / Admin Login</Link></div></div><div className="footer-bottom">© {new Date().getFullYear()} Kalidad Pharmacy. Your health, your wealth.</div></footer>}
function Home(){return <><section className="hero"><div className="hero-copy"><span className="eyebrow">WHAT WE OFFER</span><h1>Care centred<br/><i>around you</i></h1><p>From prescription filling and free health checks to wellness, personal care and baby essentials.</p><div className="hero-actions"><Link className="primary" to="/services">Explore Our Services <ArrowRight/></Link><Link className="secondary" to="/store">Shop Online <ShoppingCart/></Link></div></div><div className="hero-image"><img src={`${BASE}kalidad_pharmacy_scene.webp`} alt="Pharmacist helping a customer"/></div></section><section className="section"><div className="section-head"><span>WHY KALIDAD</span><h2>Care you can trust, every day.</h2><p>Professional pharmacy services, wellness essentials and convenient ways to reach our team.</p></div><div className="feature-grid">{[[HeartPulse,'Professional care','Pharmacist-led support for everyday health needs.'],[ShieldCheck,'Trusted service','Clear guidance and a dependable neighbourhood pharmacy.'],[Truck,'Convenient delivery','Get eligible essentials delivered around Fort Portal.']].map(([I,t,d])=><article className="feature" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section></>}
function ContentPage({data}){return <><section className="page-hero"><div><span>{data[1]}</span><h1>{data[0]}</h1><p>{data[2]}</p></div><img src={`${BASE}${data[3]}`} alt=""/></section><section className="section prose"><div><h2>Practical care for real life</h2><p>At Kalidad Pharmacy, we combine professional pharmacy support with approachable wellness guidance. Our team is here to help you understand your options, use medicines safely and find everyday health essentials.</p><p>Visit us in Kisenyi, Fort Portal, or use our online store to explore available products and place an order.</p><Link className="primary" to="/store">Explore the store <ArrowRight/></Link></div></section></>}
function Store({add}){const [products,setProducts]=useState([]),[q,setQ]=useState('');useEffect(()=>{getDocs(query(collection(db,'products'),where('active','==',true),limit(60))).then(s=>setProducts(s.docs.map(d=>({id:d.id,...d.data()})))).catch(console.error)},[]);const shown=products.filter(p=>`${p.name} ${p.categoryName||''}`.toLowerCase().includes(q.toLowerCase()));return <div className="store-page"><div className="store-head"><div><span>ONLINE PHARMACY</span><h1>Shop Kalidad</h1><p>Explore health, wellness and personal-care essentials.</p></div><Link className="primary" to="/store/cart"><ShoppingCart/> View cart</Link></div><div className="search"><Search/><input placeholder="Search products..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="product-grid">{shown.map(p=><article className="product" key={p.id}><div className="product-image">{p.image?<img src={p.image} alt=""/>:<Package/>}</div><span>{p.categoryName||'Health essential'}</span><h3>{p.name}</h3><p>{p.shortDescription||p.description||''}</p><div className="product-foot"><strong>UGX {Number(p.salePrice||p.price||0).toLocaleString()}</strong><button onClick={()=>add(p)}>Add to cart</button></div></article>)}</div>{!shown.length&&<div className="empty">No products found yet. Admin can add products from the dashboard.</div>}</div>}
function Login({signup=false,admin=false}){const [form,setForm]=useState({email:'',password:'',firstName:'',lastName:'',phone:''}),[error,setError]=useState('');const navg=useNavigate();async function submit(e){e.preventDefault();setError('');try{if(signup){const c=await createUserWithEmailAndPassword(auth,form.email,form.password);await updateProfile(c.user,{displayName:`${form.firstName} ${form.lastName}`});await setDoc(doc(db,'users',c.user.uid),{firstName:form.firstName,lastName:form.lastName,phone:form.phone,email:form.email,role:'customer',active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});navg('/store/account')}else{await signInWithEmailAndPassword(auth,form.email,form.password);navg(admin?'/admin':'/store/account')}}catch(e){setError(e.message.replace('Firebase: ','').replace(/\s*\(auth\/[^)]+\)\.?/,'').trim())}}return <div className="auth-page"><form className="auth-card" onSubmit={submit}><span>{admin?'STAFF PORTAL':signup?'CREATE ACCOUNT':'WELCOME BACK'}</span><h1>{admin?'Admin sign in':signup?'Create your Kalidad account':'Sign in to Kalidad'}</h1>{signup&&<><input placeholder="First name" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="Last name" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><input placeholder="Phone number" required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></>}<input type="email" placeholder={admin?'Admin email':'Email address'} required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" required minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button className="primary full">{admin?'Sign in':signup?'Create account':'Sign in'} <ArrowRight/></button>{!admin&&<p>{signup?'Already have an account? ':'New to Kalidad? '}<Link to={signup?'/store/login':'/store/signup'}>{signup?'Sign in':'Create an account'}</Link></p>}{admin&&<p>Authorised Kalidad staff only.</p>}</form></div>}
function Account({user}){if(!user)return <Navigate to="/store/login" replace/>;return <div className="account-page"><div className="account-hero"><span>MY ACCOUNT</span><h1>Welcome, {user.displayName?.split(' ')[0]||'Customer'}.</h1><p>Manage your Kalidad orders and account from one place.</p></div><div className="account-grid"><Link className="dashboard-card" to="/store/orders"><Package/><h3>My Orders</h3><p>View order history and delivery status.</p></Link><Link className="dashboard-card" to="/store/cart"><ShoppingCart/><h3>My Cart</h3><p>Review items ready for checkout.</p></Link><button className="dashboard-card" onClick={()=>signOut(auth)}><LogOut/><h3>Sign out</h3><p>Sign out of your Kalidad account.</p></button></div></div>}
function Cart({cart,setCart}){const total=cart.reduce((s,p)=>s+Number(p.salePrice||p.price||0)*p.quantity,0);return <div className="cart-page"><div className="store-head"><div><span>YOUR SHOPPING BAG</span><h1>Cart</h1></div><Link className="secondary" to="/store">Continue shopping</Link></div>{cart.length?<><div className="cart-list">{cart.map(p=><article key={p.id}><div className="cart-img">{p.image&&<img src={p.image} alt=""/>}</div><div><h3>{p.name}</h3><p>UGX {Number(p.salePrice||p.price||0).toLocaleString()} × {p.quantity}</p></div><button onClick={()=>setCart(c=>c.filter(x=>x.id!==p.id))}>Remove</button></article>)}</div><div className="cart-total"><strong>Total: UGX {total.toLocaleString()}</strong><Link className="primary" to="/store/checkout">Checkout <ArrowRight/></Link></div></>:<div className="empty">Your cart is empty. <Link to="/store">Start shopping</Link></div>}</div>}
function Checkout({cart,setCart}){const [address,setAddress]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false);const navg=useNavigate();async function place(){if(!auth.currentUser){navg('/store/login');return}if(!address||!phone)return alert('Please enter your delivery address and phone number.');setBusy(true);try{const subtotal=cart.reduce((s,p)=>s+Number(p.salePrice||p.price||0)*p.quantity,0);const ref=await addDoc(collection(db,'orders'),{orderNumber:`KAL-${Math.random().toString(36).slice(2,8).toUpperCase()}`,userId:auth.currentUser.uid,customer:{name:auth.currentUser.displayName||auth.currentUser.email,phone},items:cart.map(p=>({productId:p.id,name:p.name,price:Number(p.salePrice||p.price||0),quantity:p.quantity})),subtotal,deliveryFee:0,total:subtotal,paymentMethod:'cash_on_delivery',paymentStatus:'pending',orderStatus:'pending',deliveryAddress:{address,phone},createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setCart([]);navg(`/store/order/${ref.id}`)}catch(e){alert(e.message)}finally{setBusy(false)}}return <div className="checkout"><span>CHECKOUT</span><h1>Complete your order</h1><div className="checkout-card"><label>Delivery address<textarea value={address} onChange={e=>setAddress(e.target.value)} placeholder="Your delivery address"/></label><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+256..."/></label><p>Payment: <strong>Cash on delivery</strong></p><button className="primary full" disabled={busy} onClick={place}>{busy?'Placing order...':'Place order'} <ArrowRight/></button></div></div>}
function Orders({user}){const [orders,setOrders]=useState([]);useEffect(()=>{if(user)getDocs(query(collection(db,'orders'),where('userId','==',user.uid),orderBy('createdAt','desc'))).then(s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()})))).catch(console.error)},[user]);if(!user)return <Navigate to="/store/login" replace/>;return <div className="account-page"><div className="account-hero"><span>MY ORDERS</span><h1>Order history</h1></div><div className="orders-list">{orders.map(o=><Link to={`/store/order/${o.id}`} className="order-row" key={o.id}><div><strong>{o.orderNumber||o.id}</strong><p>{o.items?.length||0} item(s) · UGX {Number(o.total||0).toLocaleString()}</p></div><span>{o.orderStatus||'pending'}</span></Link>)}{!orders.length&&<div className="empty">No orders yet. <Link to="/store">Start shopping</Link></div>}</div></div>}
function OrderDetail({user}){const {id}=useParams();const [o,setO]=useState(null);useEffect(()=>{if(user)getDoc(doc(db,'orders',id)).then(s=>{if(s.exists()&&s.data().userId===user.uid)setO({id:s.id,...s.data()})})},[user,id]);if(!user)return <Navigate to="/store/login" replace/>;if(!o)return <div className="empty">Loading order…</div>;return <div className="account-page"><div className="account-hero"><span>ORDER</span><h1>{o.orderNumber||o.id}</h1><p>Status: {o.orderStatus||'pending'}</p></div><section className="section prose"><div><h2>Order summary</h2>{(o.items||[]).map(i=><p key={i.productId}>{i.name} × {i.quantity} — UGX {Number(i.price*i.quantity).toLocaleString()}</p>)}<p><strong>Total: UGX {Number(o.total||0).toLocaleString()}</strong></p><Link className="primary" to="/store/orders">Back to orders</Link></div></section></div>}
function Admin(){const [user,setUser]=useState(auth.currentUser),[products,setProducts]=useState([]);useEffect(()=>onAuthStateChanged(auth,setUser),[]);useEffect(()=>{if(user)getDoc(doc(db,'users',user.uid)).then(s=>{if(!s.exists()||!['admin','superadmin','staff'].includes(s.data().role))signOut(auth)})},[user]);useEffect(()=>{if(user)getDocs(query(collection(db,'products'),limit(50))).then(s=>setProducts(s.docs.map(d=>({id:d.id,...d.data()}))))},[user]);if(!user)return <Navigate to="/admin/login" replace/>;return <div className="admin"><aside><div className="admin-brand">KALIDAD<br/><small>ADMIN</small></div><Link to="/admin">Dashboard</Link><Link to="/admin/products">Products</Link><Link to="/admin/orders">Orders</Link><Link to="/admin/customers">Customers</Link><Link to="/admin/content">Website Content</Link><button onClick={()=>signOut(auth)}>Sign out</button></aside><main><span>ADMINISTRATION</span><h1>Dashboard</h1><div className="admin-stats"><div><Package/><b>{products.length}</b><span>Products</span></div><div><ShoppingCart/><b>Orders</b><span>Manage customer orders</span></div><div><UserRound/><b>Customers</b><span>Manage accounts</span></div></div><section className="admin-panel"><h2>Quick actions</h2><div className="quick"><Link to="/admin/products">Manage products <ArrowRight/></Link><Link to="/admin/orders">Review orders <ArrowRight/></Link><Link to="/store">View store <ArrowRight/></Link></div></section></main></div>}
function App(){const [dark,toggle]=useTheme(),[user,setUser]=useState(null);const {cart,setCart,add}=useCart();useEffect(()=>onAuthStateChanged(auth,setUser),[]);return <><Header user={user} count={cart.reduce((n,p)=>n+p.quantity,0)} dark={dark} toggle={toggle}/><Routes><Route path="/" element={<Home/>}/><Route path="/store" element={<Store add={add}/>}/><Route path="/store/login" element={<Login/>}/><Route path="/store/signup" element={<Login signup/>}/><Route path="/store/account" element={<Account user={user}/>}/><Route path="/store/cart" element={<Cart cart={cart} setCart={setCart}/>}/><Route path="/store/checkout" element={<Checkout cart={cart} setCart={setCart}/>}/><Route path="/store/orders" element={<Orders user={user}/>}/><Route path="/store/order/:id" element={<OrderDetail user={user}/>}/><Route path="/admin/login" element={<Login admin/>}/><Route path="/admin/*" element={<Admin/>}/>{Object.entries(pages).map(([p,d])=><Route key={p} path={p} element={<ContentPage data={d}/>}/>)}<Route path="*" element={<Navigate to="/" replace/>}/></Routes><Footer/></>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
